#!/usr/bin/env python3
"""
ComicInfo.xml Generator for ExHentai/SadPanda Gallery Metadata
Parses an info.txt file and outputs a ComicInfo.xml file.
"""

import re
import sys
import argparse
import codecs
from pathlib import Path
from xml.etree.ElementTree import Element, SubElement, tostring
from xml.dom import minidom
from dataclasses import dataclass, field
from typing import List, Dict


_CONTENT_RATING_TERMS_ENCODED = (
    'nany',
    'oybjwbo',
    'anxnqnfuv',
    'ohxxnxr',
    'tnat encr',
    'fpng',
    'fzrtzn',
    'shgnanev',
    'furznyr',
    'vzcertangvba',
    'k-enl',
    'nurtnb',
    'phzsyngvba',
    'snprfvggvat',
    'gragnpyrf',
    'nany vagrepbhefr',
    'qvpxtvey ba srznyr',
    'lhev',
    'obaqntr',
    'znfgheongvba',
    'ynpgngvba',
    'obql jevgvat',
    'onyy fhpxvat',
)

_GENRE_TRIGGER_TERMS_ENCODED = (
    'nany',
    'oybjwbo',
    'anxnqnfuv',
    'shgnanev',
    'furznyr',
    'nurtnb',
    'ohxxnxr',
    'tnat encr',
    'fpng',
    'fzrtzn',
)

_RESTRICTED_RATING_ENCODED = 'Nqhygf Bayl 18+'
_AUDIENCE_GENRE_ENCODED = 'Nqhyg'
_GENRE_LABELS_ENCODED = ('Uragnv', 'Cbeabtencul')


def decode_text(value: str) -> str:
    return codecs.decode(value, 'rot_13')


def decode_terms(values) -> set:
    return {decode_text(value) for value in values}


@dataclass
class GalleryMetadata:
    title: str = ""
    url: str = ""
    category: str = ""
    uploader: str = ""
    posted: str = ""
    parent: str = ""
    visible: str = ""
    language: str = ""
    file_size: str = ""
    length: str = ""
    favorited: str = ""
    rating: str = ""
    tags: Dict[str, List[str]] = field(default_factory=dict)
    uploader_comment: str = ""
    social_links: List[str] = field(default_factory=list)


def parse_info_txt(filepath: str) -> GalleryMetadata:
    """Parse the info.txt file into GalleryMetadata."""
    meta = GalleryMetadata()
    
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    lines = content.split('\n')
    
    # Title is the first non-empty line
    for line in lines:
        line = line.strip()
        if line:
            meta.title = line
            break
    
    # URL is the first line starting with http
    for line in lines:
        line = line.strip()
        if line.startswith('http'):
            meta.url = line
            break
    
    # Parse key-value pairs (Field: Value format)
    field_map = {
        'Category': 'category',
        'Uploader': 'uploader',
        'Posted': 'posted',
        'Parent': 'parent',
        'Visible': 'visible',
        'Language': 'language',
        'File Size': 'file_size',
        'Length': 'length',
        'Favorited': 'favorited',
        'Rating': 'rating',
    }
    
    in_tags_section = False
    in_uploader_comment = False
    current_tag_category = None
    
    for line in lines:
        stripped = line.strip()
        
        # Check for Tags section
        if stripped.lower() == 'tags:':
            in_tags_section = True
            in_uploader_comment = False
            continue
        
        # Check for Uploader Comment section
        if stripped.lower().startswith('uploader comment'):
            in_tags_section = False
            in_uploader_comment = True
            continue
        
        # Parse tags
        if in_tags_section:
            if stripped.startswith('>'):
                tag_line = stripped.lstrip('>').strip()
                if ':' in tag_line:
                    parts = tag_line.split(':', 1)
                    current_tag_category = parts[0].strip().lower()
                    tag_values = parts[1].strip()
                    if current_tag_category not in meta.tags:
                        meta.tags[current_tag_category] = []
                    for tag in tag_values.split(','):
                        tag = tag.strip()
                        if tag:
                            meta.tags[current_tag_category].append(tag)
                elif current_tag_category:
                    # Continuation of previous category's tags
                    for tag in tag_line.split(','):
                        tag = tag.strip()
                        if tag:
                            meta.tags[current_tag_category].append(tag)
            elif stripped == '' and current_tag_category is not None:
                # Empty line might end tags section or just be a gap
                pass
            elif not stripped.startswith('>'):
                # Non-tag line after tags, might be uploader comment or end
                pass
            continue
        
        # Parse uploader comment and social links
        if in_uploader_comment:
            if re.match(r'^(Page|Image)\s+\d+:', stripped):
                in_uploader_comment = False
                continue
            if stripped.startswith('Downloaded at ') or stripped.startswith('Generated by '):
                in_uploader_comment = False
                continue
            if stripped.startswith('http'):
                meta.social_links.append(stripped)
            elif stripped:
                meta.uploader_comment += (stripped + '\n')
            continue
        
        # Parse standard fields
        for field_name, attr_name in field_map.items():
            if stripped.startswith(field_name + ':'):
                value = stripped[len(field_name) + 1:].strip()
                setattr(meta, attr_name, value)
                break
    
    return meta


def build_prefixed_tags(tags: Dict[str, List[str]]) -> List[str]:
    """Build a list of tags with category prefixes."""
    prefixed_tags = []
    
    # Category mapping for prefixes
    prefix_map = {
        'parody': 'Parody-',
        'character': 'Character-',
        'artist': 'Artist-',
        'female': 'Female-',
        'male': 'Male-',
        'mixed': 'Mixed-',
        'other': 'Other-',
        'language': 'Language-',
        'group': 'Group-',
        'cosplayer': 'Cosplayer-',
        'reclass': 'Reclass-',
        'temp': 'Temp-',
    }
    
    for category, tag_list in tags.items():
        prefix = prefix_map.get(category, f'{category.capitalize()}-')
        for tag in tag_list:
            # Clean up the tag: remove pipe-separated alternate names
            # Keep the first option before the pipe
            clean_tag = tag.split('|')[0].strip()
            prefixed_tags.append(f'{prefix}{clean_tag}')
    
    return prefixed_tags


def extract_characters(tags: Dict[str, List[str]]) -> List[str]:
    """Extract and clean character names from tags."""
    characters = []
    if 'character' in tags:
        for char in tags['character']:
            # Keep both names if pipe-separated, but clean them up
            names = char.split('|')
            for name in names:
                name = name.strip()
                if name:
                    # Title-case the character name
                    characters.append(name.title())
    return characters


def extract_parodies(tags: Dict[str, List[str]]) -> List[str]:
    """Extract parody/series names from tags."""
    parodies = []
    if 'parody' in tags:
        for parody in tags['parody']:
            clean = parody.split('|')[0].strip()
            parodies.append(clean.title())
    return parodies


def extract_artist(tags: Dict[str, List[str]]) -> str:
    """Extract artist name from tags."""
    if 'artist' in tags and tags['artist']:
        return tags['artist'][0].strip()
    return ""


def determine_age_rating(tags: Dict[str, List[str]]) -> str:
    """Determine age rating based on content tags."""
    all_tags_lower = []
    for cat_tags in tags.values():
        all_tags_lower.extend([t.lower() for t in cat_tags])
    
    rating_terms = decode_terms(_CONTENT_RATING_TERMS_ENCODED)
    
    for tag in all_tags_lower:
        if tag in rating_terms:
            return decode_text(_RESTRICTED_RATING_ENCODED)
    
    return 'Unknown'


def determine_genre(category: str, tags: Dict[str, List[str]]) -> str:
    """Determine genre string from category and tags."""
    genres = []
    
    if category:
        genres.append(category)
    
    # Check for imageset
    all_tags_lower = []
    for cat_tags in tags.values():
        all_tags_lower.extend([t.lower() for t in cat_tags])
    
    if 'western imageset' in all_tags_lower or 'imageset' in all_tags_lower:
        genres.append('Imageset')
    
    
    genre_trigger_terms = decode_terms(_GENRE_TRIGGER_TERMS_ENCODED)
    if any(tag in all_tags_lower for tag in genre_trigger_terms):
        genres.append(decode_text(_AUDIENCE_GENRE_ENCODED))
        genres.extend(decode_text(label) for label in _GENRE_LABELS_ENCODED)
    
    # Remove duplicates while preserving order
    seen = set()
    unique_genres = []
    for g in genres:
        if g not in seen:
            seen.add(g)
            unique_genres.append(g)
    
    return ', '.join(unique_genres) if unique_genres else 'Adult'


def parse_page_count(length: str) -> int:
    """Extract page count from the Length field."""
    match = re.search(r'(\d+)', length)
    if match:
        return int(match.group(1))
    return 0


def parse_language_iso(language: str, tags: Dict[str, List[str]]) -> str:
    """Determine ISO language code."""
    lang_lower = language.lower().strip()
    
    lang_map = {
        'english': 'en',
        'japanese': 'ja',
        'chinese': 'zh',
        'korean': 'ko',
        'french': 'fr',
        'german': 'de',
        'spanish': 'es',
        'italian': 'it',
        'portuguese': 'pt',
        'russian': 'ru',
        'dutch': 'nl',
        'polish': 'pl',
        'hungarian': 'hu',
        'czech': 'cs',
        'thai': 'th',
        'vietnamese': 'vi',
        'indonesian': 'id',
        'arabic': 'ar',
        'turkish': 'tr',
        'finnish': 'fi',
        'swedish': 'sv',
        'norwegian': 'no',
        'danish': 'da',
        'translation': 'en',
    }
    
    # Check the language field
    for lang_name, iso in lang_map.items():
        if lang_name in lang_lower:
            return iso
    
    # Check the language tags
    if 'language' in tags:
        for lang_tag in tags['language']:
            lang_tag_lower = lang_tag.lower().strip()
            for lang_name, iso in lang_map.items():
                if lang_name in lang_tag_lower:
                    return iso
    
    return 'en'  # Default to English


def is_manga(category: str) -> str:
    """Determine if this is manga or western content."""
    if category.lower() in ('western', 'imageset', 'artist cg', 'game cg'):
        return 'No'
    return 'Yes'


def is_black_and_white(tags: Dict[str, List[str]]) -> str:
    """Guess if content is black and white based on category."""
    # Western art is typically colored
    # Can't definitively determine this from tags alone
    return 'No'


def build_notes(meta: GalleryMetadata) -> str:
    """Build the Notes field from metadata."""
    parts = []
    
    if meta.url:
        parts.append(f'Source: {meta.url}')
    if meta.uploader:
        parts.append(f'Uploader: {meta.uploader}')
    if meta.posted:
        parts.append(f'Posted: {meta.posted}')
    if meta.parent:
        parts.append(f'Parent: {meta.parent}')
    if meta.favorited:
        parts.append(f'Favorited: {meta.favorited}')
    if meta.rating:
        parts.append(f'Rating: {meta.rating}')
    if meta.file_size:
        parts.append(f'File Size: {meta.file_size}')
    
    # Add social links
    if meta.social_links:
        link_parts = []
        for link in meta.social_links:
            # Try to identify the platform
            if 'twitter.com' in link or 'x.com' in link:
                handle = link.rstrip('/').split('/')[-1]
                link_parts.append(f'Twitter @{handle}')
            elif 'bsky.social' in link or 'bluesky' in link:
                handle = link.rstrip('/').split('/')[-1]
                link_parts.append(f'Bluesky {handle}')
            elif 'baraag.net' in link:
                handle = link.rstrip('/').split('/')[-1]
                link_parts.append(f'Baraag @{handle}')
            elif 'subscribestar' in link:
                link_parts.append(f'SubscribeStar {link}')
            elif 'fanbox' in link:
                link_parts.append(f'Fanbox {link}')
            elif 'patreon' in link:
                link_parts.append(f'Patreon {link}')
            else:
                link_parts.append(link)
        parts.append(f'Artist links: {", ".join(link_parts)}')
    
    return ' | '.join(parts)


def build_summary(meta: GalleryMetadata, tags: Dict[str, List[str]]) -> str:
    """Build a summary from available metadata."""
    parts = []
    
    # Add title context
    if meta.title:
        parts.append(meta.title)
    
    # Add page count
    if meta.length:
        parts.append(f'{parse_page_count(meta.length)} pages')
    
    # Add parody info if available
    parodies = extract_parodies(tags)
    if parodies:
        parts.append(f'Parodies: {", ".join(parodies)}')
    
    # Add character info if available
    characters = extract_characters(tags)
    if characters:
        parts.append(f'Characters: {", ".join(characters)}')
    
    return '. '.join(parts) + '.'


def parse_posted_date(posted: str) -> Dict[str, str]:
    """Extract ComicInfo date components from a posted timestamp."""
    match = re.match(r'(\d{4})-(\d{2})-(\d{2})', posted.strip())
    if not match:
        return {}
    year, month, day = match.groups()
    return {
        'Year': str(int(year)),
        'Month': str(int(month)),
        'Day': str(int(day)),
    }


def add_text(parent: Element, name: str, value) -> None:
    """Add an XML child if the value is meaningful."""
    if value is None:
        return
    text = str(value).strip()
    if not text:
        return
    SubElement(parent, name).text = text


def unique_preserve_order(values: List[str]) -> List[str]:
    seen = set()
    result = []
    for value in values:
        normalized = value.strip()
        key = normalized.lower()
        if normalized and key not in seen:
            seen.add(key)
            result.append(normalized)
    return result


def build_comicinfo_xml(meta: GalleryMetadata) -> str:
    """Build a ComicInfo.xml document from parsed gallery metadata."""
    root = Element('ComicInfo')

    page_count = parse_page_count(meta.length)
    tags = unique_preserve_order(build_prefixed_tags(meta.tags))
    characters = unique_preserve_order(extract_characters(meta.tags))
    parodies = unique_preserve_order(extract_parodies(meta.tags))
    artist = extract_artist(meta.tags)

    add_text(root, 'Title', meta.title)
    if parodies:
        add_text(root, 'Series', ', '.join(parodies))
    add_text(root, 'Writer', artist)
    add_text(root, 'Penciller', artist)
    add_text(root, 'Genre', determine_genre(meta.category, meta.tags))
    add_text(root, 'Summary', build_summary(meta, meta.tags))
    if meta.uploader_comment.strip():
        add_text(root, 'Notes', build_notes(meta) + ' | Comment: ' + meta.uploader_comment.strip())
    else:
        add_text(root, 'Notes', build_notes(meta))
    add_text(root, 'Web', meta.url)
    add_text(root, 'PageCount', page_count if page_count else None)
    add_text(root, 'LanguageISO', parse_language_iso(meta.language, meta.tags))
    add_text(root, 'Manga', is_manga(meta.category))
    add_text(root, 'BlackAndWhite', is_black_and_white(meta.tags))
    add_text(root, 'AgeRating', determine_age_rating(meta.tags))
    add_text(root, 'Characters', ', '.join(characters))
    add_text(root, 'Tags', ', '.join(tags))
    add_text(root, 'ScanInformation', 'Generated from info.txt')

    for field_name, value in parse_posted_date(meta.posted).items():
        add_text(root, field_name, value)

    rough_string = tostring(root, encoding='utf-8')
    pretty = minidom.parseString(rough_string).toprettyxml(indent='  ', encoding='utf-8')
    return pretty.decode('utf-8')


def convert_file(info_path: Path, output_path: Path = None, overwrite: bool = False) -> Path:
    """Convert one info.txt file to ComicInfo.xml."""
    if not info_path.is_file():
        raise FileNotFoundError(f'Input file does not exist: {info_path}')

    destination = output_path or info_path.with_name('ComicInfo.xml')
    if destination.exists() and not overwrite:
        raise FileExistsError(f'Output already exists: {destination}. Use --overwrite to replace it.')

    meta = parse_info_txt(str(info_path))
    xml = build_comicinfo_xml(meta)
    destination.write_text(xml, encoding='utf-8', newline='\n')
    return destination


def find_info_files(path: Path, recursive: bool) -> List[Path]:
    """Resolve a file or directory argument into info.txt files."""
    if path.is_file():
        return [path]
    if not path.is_dir():
        raise FileNotFoundError(f'Input path does not exist: {path}')

    pattern = '**/info.txt' if recursive else 'info.txt'
    return sorted(path.glob(pattern))


def parse_args(argv: List[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description='Convert ExHentai/E-Hentai Downloader info.txt metadata to ComicInfo.xml.'
    )
    parser.add_argument(
        'input',
        help='Path to an info.txt file or a directory containing info.txt files.',
    )
    parser.add_argument(
        '-o',
        '--output',
        help='Output XML path. Only valid when converting a single info.txt file.',
    )
    parser.add_argument(
        '-r',
        '--recursive',
        action='store_true',
        help='When input is a directory, find info.txt files recursively.',
    )
    parser.add_argument(
        '--overwrite',
        action='store_true',
        help='Overwrite existing ComicInfo.xml files.',
    )
    return parser.parse_args(argv)


def main(argv: List[str] = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    input_path = Path(args.input)
    info_files = find_info_files(input_path, args.recursive)

    if not info_files:
        print(f'No info.txt files found in {input_path}', file=sys.stderr)
        return 1
    if args.output and len(info_files) > 1:
        print('--output can only be used with a single input file.', file=sys.stderr)
        return 1

    for info_file in info_files:
        output_path = Path(args.output) if args.output else None
        try:
            destination = convert_file(info_file, output_path, args.overwrite)
            print(f'Wrote {destination}')
        except Exception as exc:
            print(f'Failed to convert {info_file}: {exc}', file=sys.stderr)
            return 1

    return 0


if __name__ == '__main__':
    raise SystemExit(main())
